apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-a
spec:
  selector:
    matchLabels:
      app: server-a
      tier: backend
      track: stable
  replicas: 1
  template:
    metadata:
      labels:
        app: server-a
        tier: backend
        track: stable
    spec:
      containers:
        - name: flapi
          image: "wiss013/demo-server_a"
          ports:
            - name: http
              containerPort: 8000

  

